services:
  questionnaire-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: convenienttrial
      MYSQL_TCP_PORT: 3306
    volumes:
      - questionnaire_data:/var/lib/mysql
      - ./encryption_service/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  questionnaire-service:
    build: ./questionnaire_service/
    depends_on:
      - questionnaire-db
    ports:
      - "8000:8000"

  encryption-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: convenienttrial
      MYSQL_TCP_PORT: 3307
    volumes:
      - encryption_data:/var/lib/mysql
      - ./encryption_service/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "3307:3307"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  encryption-service:
    build: ./encryption_service
    depends_on:
      - encryption-db
    ports:
      - "8001:8000"

  authentication-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: convenienttrial
      MYSQL_TCP_PORT: 3308
    volumes:
      - authentication_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "3308:3308"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  authentication-service:
    build: ./authentication_service/
    environment:
      MYSQL_SERVER: db
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: convenienttrial
    depends_on:
      - authentication-db
    ports:
      - "8002:8000"

  patient-bff:
    build: ./patient_bff/
    environment:
      AUTHENTICATION_SERVICE_URL: "http://authentication-service:8000"
      ENCRYPTION_SERVICE_URL: "http://encryption-service:8000"
      QUESTIONNAIRE_SERVICE_URL: "http://questionnaire-service:8000"
    depends_on:
      - authentication-service
      - encryption-service
      - questionnaire-service
    ports:
      - "8003:8000"

  react-frontend:
    build:
      context: ./patient_frontend/
      args:
        - REACT_APP_BFF_URL=http://localhost:8003
    ports:
      - "3000:80"
    depends_on:
      - patient-bff

volumes:
  questionnaire_data:
  encryption_data:
  authentication_data:
