services:
  authentication-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: convenienttrial
      MYSQL_TCP_PORT: 3308
    volumes:
      - authentication_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "3308:3308"

  authentication-service:
    build: .
    environment:
      MYSQL_SERVER: db
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: convenienttrial
    depends_on:
      - authentication-db
    ports:
      - "8002:8000"

volumes:
  authentication_data:
